apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"apps"},"name":"metallb","namespace":"argocd"},"spec":{"destination":{"namespace":"metallb-system","server":"https://kubernetes.default.svc"},"project":"default","source":{"kustomize":{"version":"v4.5.4"},"path":"distribution/metallb","repoURL":"https://github.com/gkranasinghe/k8s","targetRevision":"master"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2022-09-27T07:56:06Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-09-27T23:18:16Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 139
  labels:
    app.kubernetes.io/instance: apps
  name: metallb
  namespace: argocd
  resourceVersion: "142098"
  uid: 835693fc-f430-4794-a1be-f71040c9177b
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.5.4
    path: distribution/metallb
    repoURL: https://github.com/gkranasinghe/k8s
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  conditions:
  - lastTransitionTime: "2022-09-27T23:16:06Z"
    message: |-
      rpc error: code = Unknown desc = Manifest generation error (cached): `/custom-tools/kustomize_4_5_4 build .distribution/metallb --enable-helm` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from 'base': '.distribution/metallb/base' must resolve to a file': recursed accumulation of path '.distribution/metallb/base': Error: execution error at (metallb/templates/deprecated_configInline.yaml:2:4): Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility

      Use --debug flag to render out invalid YAML
      : unable to run: 'helm template metallb --namespace metallb-system .distribution/metallb/base/charts/metallb --values /tmp/kustomize-helm-753902470/metallb-kustomize-values.yaml' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-753902470/helm HELM_CACHE_HOME=/tmp/kustomize-helm-753902470/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-753902470/helm/.data] (is 'helm' installed?)
    type: ComparisonError
  health:
    status: Healthy
  operationState:
    finishedAt: "2022-09-27T12:16:13Z"
    message: |-
      ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): `/custom-tools/kustomize_4_5_4 build .distribution/metallb --enable-helm` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from 'base': '.distribution/metallb/base' must resolve to a file': recursed accumulation of path '.distribution/metallb/base': Error: execution error at (metallb/templates/deprecated_configInline.yaml:2:4): Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility

      Use --debug flag to render out invalid YAML
      : unable to run: 'helm template metallb --namespace metallb-system .distribution/metallb/base/charts/metallb --values /tmp/kustomize-helm-1751164292/metallb-kustomize-values.yaml' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-1751164292/helm HELM_CACHE_HOME=/tmp/kustomize-helm-1751164292/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-1751164292/helm/.data] (is 'helm' installed?)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 266669bd58383a7bad0fe57a44dbe52417692c81
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Error
    startedAt: "2022-09-27T12:16:13Z"
    syncResult:
      revision: ""
      source:
        kustomize:
          version: v4.5.4
        path: distribution/metallb
        repoURL: https://github.com/gkranasinghe/k8s
        targetRevision: master
  reconciledAt: "2022-09-27T23:16:06Z"
  resources:
  - kind: ConfigMap
    name: metallb
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - kind: ServiceAccount
    name: metallb-controller
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - kind: ServiceAccount
    name: metallb-speaker
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: DaemonSet
    name: metallb-speaker
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: metallb-controller
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - group: policy
    kind: PodSecurityPolicy
    name: metallb-controller
    requiresPruning: true
    status: Unknown
    version: v1beta1
  - group: policy
    kind: PodSecurityPolicy
    name: metallb-speaker
    requiresPruning: true
    status: Unknown
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metallb:controller
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metallb:speaker
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: metallb:controller
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: metallb:speaker
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: metallb-config-watcher
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: metallb-controller
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: metallb-pod-lister
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: metallb-config-watcher
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: metallb-controller
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: metallb-pod-lister
    namespace: metallb-system
    requiresPruning: true
    status: Unknown
    version: v1
  summary:
    images:
    - quay.io/metallb/controller:v0.12.1
    - quay.io/metallb/speaker:v0.12.1
  sync:
    comparedTo:
      destination:
        namespace: metallb-system
        server: https://kubernetes.default.svc
      source:
        kustomize:
          version: v4.5.4
        path: distribution/metallb
        repoURL: https://github.com/gkranasinghe/k8s
        targetRevision: master
    status: Unknown
