apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gkranasinghe/k8s
    targetRevision: master
    path: distribution/metallb
    kustomize:
      version: v4.5.4
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
