apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  kustomize.version.v4.5.4: /custom-tools/kustomize_4_5_4
  kustomize.buildOptions: --enable-helm