
- hosts: localhost
  vars: 
     input_values_file: "airflow-values-upgrade-input.yaml"
  tasks:
    - name: Airflow upgrade with Helm
      shell: |
                helm upgrade --install airflow apache-airflow/airflow  -n airflow -f "{{ input_values_file }}" --debug --timeout 10m0s

    - name: wait for pods to come up
      shell: kubectl get pods -n airflow  -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
      retries: 10
      delay: 30

    - name: Patch airflow service as loadbalancer
      shell: |
                kubectl patch svc airflow-webserver -n airflow  -p '{"spec": {"type": "LoadBalancer"}}'

    # - name: get values.yaml
    #   shell: |
    #             helm show values apache-airflow/airflow > airflow-values.yaml
#helm upgrade --install airflow apache-airflow/airflow  -n airflow -f airflow-values.yaml