- hosts: localhost
  vars: 
     k8_name_space: "postgresql"
  tasks:
    - name: Add postgresql namespace
      shell: |
                kubectl create namespace {{k8_name_space}}

    # - name: create pvc for pgsql from an inline definition
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: v1
    #       kind: PersistentVolumeClaim
    #       metadata:
    #         name: postgresql-pvc
    #         namespace: postgresql
    #       spec:
    #         accessModes:
    #           - ReadWriteOnce
    #         resources:
    #           requests:
    #             storage: 1Gi


    - name: install with helm charts 
      shell: |
              helm repo add bitnami https://charts.bitnami.com/bitnami
              helm install postgresql bitnami/postgresql --namespace {{k8_name_space}}

    - name: wait for pods to come up
      shell: kubectl get pods -n {{k8_name_space}}  -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
      retries: 10
      delay: 30

    # - name: cp data for seeding  
    #   shell: |
    #             kubectl cp data.dump  {{k8_name_space}}/postgresql-0:/tmp  -c postgresql
           
    - name: Patch postgresql service as loadbalancer
      shell: |
                kubectl patch svc postgresql -n postgresql  -p '{"spec": {"type": "LoadBalancer"}}'


# NAME: postgresql
# LAST DEPLOYED: Fri Sep 30 10:03:39 2022
# NAMESPACE: postgresql
# STATUS: deployed
# REVISION: 1
# TEST SUITE: None
# NOTES:
# CHART NAME: postgresql
# CHART VERSION: 11.9.2
# APP VERSION: 14.5.0

# ** Please be patient while the chart is being deployed **

# PostgreSQL can be accessed via port 5432 on the following DNS names from within your cluster:

#     postgresql.postgresql.svc.cluster.local - Read/Write connection

# To get the password for "postgres" run:

#     export POSTGRES_PASSWORD=$(kubectl get secret --namespace postgresql postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)
#postgres
#HKNEEO1tI7
# To connect to your database run the following command:

#     kubectl run postgresql-client --rm --tty -i --restart='Never' --namespace postgresql --image docker.io/bitnami/postgresql:14.5.0-debian-11-r14 --env="PGPASSWORD=$POSTGRES_PASSWORD" \
#       --command -- psql --host postgresql -U postgres -d postgres -p 5432

#     > NOTE: If you access the container using bash, make sure that you execute "/opt/bitnami/scripts/postgresql/entrypoint.sh /bin/bash" in order to avoid the error "psql: local user with ID 1001} does not exist"

# To connect to your database from outside the cluster execute the following commands:

#     kubectl port-forward --namespace postgresql svc/postgresql 5432:5432 &
#     PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432