
- hosts: localhost
  vars: 
     dag_location: "../../_airflow/dags/"
     dockerfile_location: '../../_airflow'
     airflow_version: 2.3.0
     docker_registry: localhost:5000
     image_tag: 0.0.2
  tasks:

      - name: Create a Dockerfile with permissions
        file:
            path: "{{ dockerfile_location }}/Dockerfile"
            state: touch
            mode: 0777
            owner: gk

      - name: add Dockerfile  content
        copy:
            dest: "{{ dockerfile_location }}/Dockerfile"
            content: |
                  FROM apache/airflow:{{ airflow_version }}

                  COPY  --chown=airflow:root ./dags/* /opt/airflow/dags/

      - name: add docker-context-files folder
        shell: |  
                  mkdir -p "{{ dockerfile_location }}/docker-context-files"

      - name: add requirements.txt  content
        copy:
            dest: "{{ dockerfile_location }}/docker-context-files/requirements.txt"
            content: |
                  beautifulsoup4==4.10.0
     
      - name: docker build 
        shell: |    
                 docker build "{{ dockerfile_location }}" \
                 --build-arg DOCKER_CONTEXT_FILES="{{ dockerfile_location }}/docker-context-files" \
                 --tag "{{ docker_registry }}/my-airflow:{{image_tag}}"

      - name: docker build 
        shell: |    
                docker push  {{docker_registry}}/my-airflow:2.3.0     
      
      # - name: Tag and push to docker hub
      #   community.docker.docker_image:
      #     name: pacur/centos-7:56
      #     repository: gkranasinghe/myimage:7.56
      #     push: true
      #     source: local

# docker run -it my-airflow:2.3.0 python -c 'import bs4; import sys; sys.exit(0)' && \
#     echo "Success! Beautifulsoup4 installed" && echo

#docker run -d -p 5000:5000 --restart=always --name registry registry:2