
- hosts: localhost
  vars: 
     dag_location: "../../_airflow/dags/"
     Dockerfile_location: '../../_airflow'
     airflowVersion: 2.3.0

  tasks:

      - name: Create a Dockerfile with permissions
        file:
            path: "{{ Dockerfile_location }}/Dockerfile"
            state: touch
            mode: 0777
            owner: gk

      - name: add Dockerfile  content
        copy:
            dest: "{{ Dockerfile_location }}/Dockerfile"
            content: |
                  FROM apache/airflow:{{ airflowVersion }}

                  COPY  --chown=airflow:root ./dags/* /opt/airflow/dags/

      - name: add docker-context-files folder
        shell: |  
                  mkdir -p "{{ Dockerfile_location }}/docker-context-files"

      - name: add requirements.txt  content
        copy:
            dest: "{{ Dockerfile_location }}/docker-context-files/requirements.txt"
            content: |
                  beautifulsoup4==4.10.0
     
      - name: docker build
        shell: |    
                 docker build "{{ Dockerfile_location }}" \
                 --build-arg DOCKER_CONTEXT_FILES="{{ Dockerfile_location }}/docker-context-files" \
                 --tag "gkranasinghe/my-airflow:2.3.0"
      
      
      # - name: Tag and push to docker hub
      #   community.docker.docker_image:
      #     name: pacur/centos-7:56
      #     repository: gkranasinghe/myimage:7.56
      #     push: true
      #     source: local

# docker run -it my-airflow:2.3.0 python -c 'import bs4; import sys; sys.exit(0)' && \
#     echo "Success! Beautifulsoup4 installed" && echo